version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    command: sh -c "npx sequelize db:migrate:undo:all && npx sequelize db:migrate && npx sequelize db:seed:all && npm run dev"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
