version: '3'

services:
  server:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    command: sh -c "npx sequelize db:migrate && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
