version: 2.1

orbs:
  my-orb:
    executors:
      default:
        docker:
          - image: circleci/node:10

    jobs:
      test:
        executor: default
        working_directory: ~/node-auth-server

        steps:
          - checkout
          - restore_cache:
              keys:
              # Find a cache corresponding to this specific package-lock.json
              - v1-npm-deps-{{ checksum "yarn.lock" }}
              # Fallback cache to be used
              - v1-npm-deps-
          - run: 'yarn'

          - save_cache:
              key: v1-npm-deps-{{ checksum "yarn.lock" }}
              paths:
                - ./node_modules

          - setup_remote_docker
          - run: 'ifconfig'
          - run: 'docker-compose -f docker-compose.test.yml down'
          - run: 'npm run test'

workflows:
  main:
    jobs:
      - my-orb/test
